# Generated by Django 2.2.1 on 2019-05-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyenerBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gonderi',
            old_name='baslik',
            new_name='sehir',
        ),
    ]
